imports:
    - php

tools:
    php_code_sniffer: true
    php_sim: true
    php_changetracking: true
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true

filter:
    paths: [src/*]
