<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'MamuzContentManagerTest\Bootstrap'                             => __DIR__ . '/test/Bootstrap.php',
    'MamuzContentManagerTest\Controller\QueryControllerFactoryTest' =>
    __DIR__ . '/test/MamuzContentManagerTest/Controller/QueryControllerFactoryTest.php',
    'MamuzContentManagerTest\Controller\QueryControllerTest'        =>
    __DIR__ . '/test/MamuzContentManagerTest/Controller/QueryControllerTest.php',
    'MamuzContentManagerTest\Entity\NullPageTest'                   =>
    __DIR__ . '/test/MamuzContentManagerTest/Entity/NullPageTest.php',
    'MamuzContentManagerTest\Entity\PageTest'                       =>
    __DIR__ . '/test/MamuzContentManagerTest/Entity/PageTest.php',
    'MamuzContentManagerTest\Mapper\Db\QueryTest'                   =>
    __DIR__ . '/test/MamuzContentManagerTest/Mapper/Db/QueryTest.php',
    'MamuzContentManagerTest\Service\FactoryTest'                   =>
    __DIR__ . '/test/MamuzContentManagerTest/DomainManager/FactoryTest.php',
    'MamuzContentManagerTest\Service\QueryFactoryTest'              =>
    __DIR__ . '/test/MamuzContentManagerTest/Service/QueryFactoryTest.php',
    'MamuzContentManagerTest\Service\QueryTest'                     =>
    __DIR__ . '/test/MamuzContentManagerTest/Service/QueryTest.php',
    'MamuzContentManager\Controller\QueryController'                =>
    __DIR__ . '/src/MamuzContentManager/Controller/QueryController.php',
    'MamuzContentManager\Controller\QueryControllerFactory'         =>
    __DIR__ . '/src/MamuzContentManager/Controller/QueryControllerFactory.php',
    'MamuzContentManager\DomainManager\Factory'                     =>
    __DIR__ . '/src/MamuzContentManager/DomainManager/Factory.php',
    'MamuzContentManager\DomainManager\ProviderInterface'           =>
    __DIR__ . '/src/MamuzContentManager/DomainManager/ProviderInterface.php',
    'MamuzContentManager\Entity\NullPage'                           =>
    __DIR__ . '/src/MamuzContentManager/Entity/NullPage.php',
    'MamuzContentManager\Entity\Page'                               =>
    __DIR__ . '/src/MamuzContentManager/Entity/Page.php',
    'MamuzContentManager\Feature\QueryInterface'                    =>
    __DIR__ . '/src/MamuzContentManager/Feature/QueryInterface.php',
    'MamuzContentManager\Mapper\Db\Query'                           =>
    __DIR__ . '/src/MamuzContentManager/Mapper/Db/Query.php',
    'MamuzContentManager\Module'                                    => __DIR__ . '/Module.php',
    'MamuzContentManager\Service\Query'                             =>
    __DIR__ . '/src/MamuzContentManager/Service/Query.php',
    'MamuzContentManager\Service\QueryFactory'                      =>
    __DIR__ . '/src/MamuzContentManager/Service/QueryFactory.php',
);
