<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'MamuzContentManager\Controller\QueryController'        =>
    __DIR__ . '/MamuzContentManager/Controller/QueryController.php',
    'MamuzContentManager\Controller\QueryControllerFactory' =>
    __DIR__ . '/MamuzContentManager/Controller/QueryControllerFactory.php',
    'MamuzContentManager\DomainManager\Factory'             =>
    __DIR__ . '/MamuzContentManager/DomainManager/Factory.php',
    'MamuzContentManager\DomainManager\ProviderInterface'   =>
    __DIR__ . '/MamuzContentManager/DomainManager/ProviderInterface.php',
    'MamuzContentManager\Entity\NullPage'                   => __DIR__ . '/MamuzContentManager/Entity/NullPage.php',
    'MamuzContentManager\Entity\Page'                       => __DIR__ . '/MamuzContentManager/Entity/Page.php',
    'MamuzContentManager\Feature\QueryInterface'            =>
    __DIR__ . '/MamuzContentManager/Feature/QueryInterface.php',
    'MamuzContentManager\Mapper\Db\Query'                   => __DIR__ . '/MamuzContentManager/Mapper/Db/Query.php',
    'MamuzContentManager\Module'                            => __DIR__ . '/MamuzContentManager/Module.php',
    'MamuzContentManager\Service\Query'                     => __DIR__ . '/MamuzContentManager/Service/Query.php',
    'MamuzContentManager\Service\QueryFactory'              =>
    __DIR__ . '/MamuzContentManager/Service/QueryFactory.php',
);
